-- Phase 0 carry-forward (before 0.6): no OAuth provider tokens at rest, and Role reduced to USER/ADMIN. Generated by
-- `prisma migrate dev --create-only`, then rewritten by hand so that every statement is idempotent: Prisma >= 7.4 runs
-- migration.sql statement by statement, not atomically, so a partially applied run must be re-applicable as is.
--
-- - Role: PRO duplicated the paid tier, which lives in Plan (User.planId). Prisma's version (create Role_new, retype
--   the column, swap the names) runs inside one DO block, which PostgreSQL executes atomically, and only while the
--   enum still has PRO: on a re-run it does nothing. A PRO user (there were none when this was written) becomes USER,
--   since PRO granted nothing beyond USER. Retyping rewrites "User" under an ACCESS EXCLUSIVE lock; it is small.
-- - Account: drops refresh_token, access_token, id_token and session_state (all empty when this was written).
--   Finlytics never calls a sign-in provider's API, so it has no reason to hold those tokens; the web app's Auth.js
--   adapter strips them before every write. Kept: type, provider, providerAccountId, expires_at, token_type, scope.

-- AlterEnum
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = '"Role"'::regtype AND enumlabel = 'PRO') THEN
    UPDATE "User" SET "role" = 'USER' WHERE "role" = 'PRO';
    CREATE TYPE "Role_new" AS ENUM ('USER', 'ADMIN');
    ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;
    ALTER TABLE "User" ALTER COLUMN "role" TYPE "Role_new" USING ("role"::text::"Role_new");
    ALTER TYPE "Role" RENAME TO "Role_old";
    ALTER TYPE "Role_new" RENAME TO "Role";
    DROP TYPE "Role_old";
    ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'USER';
  END IF;
END
$$;

-- AlterTable
ALTER TABLE "Account" DROP COLUMN IF EXISTS "access_token",
DROP COLUMN IF EXISTS "id_token",
DROP COLUMN IF EXISTS "refresh_token",
DROP COLUMN IF EXISTS "session_state";
