-- Tenancy binding (security review F3): every relation between two user-owned tables becomes a composite foreign key,
-- (<fk>, "userId") REFERENCES <parent>("id", "userId"), so a row can only reference rows of its own user. Optional ones
-- are ON DELETE NO ACTION: SET NULL would also null the required "userId". StrategyDeployment gains "userId" (NOT NULL
-- without a default, applied before any deployment existed). Also indexes every foreign key column that lacked a leading
-- index, so ON DELETE lookups never scan the child table. Generated by `prisma migrate dev --create-only`; only this
-- comment was added.

/*
  Warnings:

  - A unique constraint covering the columns `[id,userId]` on the table `AgentRun` will be added. If there are existing duplicate values, this will fail.
  - A unique constraint covering the columns `[id,userId]` on the table `BrokerAccount` will be added. If there are existing duplicate values, this will fail.
  - A unique constraint covering the columns `[id,userId]` on the table `Order` will be added. If there are existing duplicate values, this will fail.
  - A unique constraint covering the columns `[id,userId]` on the table `Strategy` will be added. If there are existing duplicate values, this will fail.
  - A unique constraint covering the columns `[id,userId]` on the table `StrategyDeployment` will be added. If there are existing duplicate values, this will fail.
  - Added the required column `userId` to the `StrategyDeployment` table without a default value. This is not possible if the table is not empty.

*/
-- DropForeignKey
ALTER TABLE "AgentSignal" DROP CONSTRAINT "AgentSignal_runId_fkey";

-- DropForeignKey
ALTER TABLE "Backtest" DROP CONSTRAINT "Backtest_strategyId_fkey";

-- DropForeignKey
ALTER TABLE "Order" DROP CONSTRAINT "Order_agentRunId_fkey";

-- DropForeignKey
ALTER TABLE "Order" DROP CONSTRAINT "Order_brokerAccountId_fkey";

-- DropForeignKey
ALTER TABLE "Order" DROP CONSTRAINT "Order_strategyDeploymentId_fkey";

-- DropForeignKey
ALTER TABLE "Position" DROP CONSTRAINT "Position_brokerAccountId_fkey";

-- DropForeignKey
ALTER TABLE "StrategyDeployment" DROP CONSTRAINT "StrategyDeployment_brokerAccountId_fkey";

-- DropForeignKey
ALTER TABLE "StrategyDeployment" DROP CONSTRAINT "StrategyDeployment_strategyId_fkey";

-- DropForeignKey
ALTER TABLE "Trade" DROP CONSTRAINT "Trade_brokerAccountId_fkey";

-- DropForeignKey
ALTER TABLE "Trade" DROP CONSTRAINT "Trade_orderId_fkey";

-- AlterTable
ALTER TABLE "StrategyDeployment" ADD COLUMN     "userId" TEXT NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "AgentRun_id_userId_key" ON "AgentRun"("id", "userId");

-- CreateIndex
CREATE INDEX "Backtest_strategyId_createdAt_idx" ON "Backtest"("strategyId", "createdAt" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "BrokerAccount_id_userId_key" ON "BrokerAccount"("id", "userId");

-- CreateIndex
CREATE INDEX "Order_agentRunId_idx" ON "Order"("agentRunId");

-- CreateIndex
CREATE UNIQUE INDEX "Order_id_userId_key" ON "Order"("id", "userId");

-- CreateIndex
CREATE UNIQUE INDEX "Strategy_id_userId_key" ON "Strategy"("id", "userId");

-- CreateIndex
CREATE INDEX "StrategyDeployment_userId_startedAt_idx" ON "StrategyDeployment"("userId", "startedAt" DESC);

-- CreateIndex
CREATE INDEX "StrategyDeployment_brokerAccountId_idx" ON "StrategyDeployment"("brokerAccountId");

-- CreateIndex
CREATE UNIQUE INDEX "StrategyDeployment_id_userId_key" ON "StrategyDeployment"("id", "userId");

-- CreateIndex
CREATE INDEX "Trade_orderId_idx" ON "Trade"("orderId");

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_brokerAccountId_userId_fkey" FOREIGN KEY ("brokerAccountId", "userId") REFERENCES "BrokerAccount"("id", "userId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_strategyDeploymentId_userId_fkey" FOREIGN KEY ("strategyDeploymentId", "userId") REFERENCES "StrategyDeployment"("id", "userId") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_agentRunId_userId_fkey" FOREIGN KEY ("agentRunId", "userId") REFERENCES "AgentRun"("id", "userId") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Trade" ADD CONSTRAINT "Trade_brokerAccountId_userId_fkey" FOREIGN KEY ("brokerAccountId", "userId") REFERENCES "BrokerAccount"("id", "userId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Trade" ADD CONSTRAINT "Trade_orderId_userId_fkey" FOREIGN KEY ("orderId", "userId") REFERENCES "Order"("id", "userId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Position" ADD CONSTRAINT "Position_brokerAccountId_userId_fkey" FOREIGN KEY ("brokerAccountId", "userId") REFERENCES "BrokerAccount"("id", "userId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "StrategyDeployment" ADD CONSTRAINT "StrategyDeployment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "StrategyDeployment" ADD CONSTRAINT "StrategyDeployment_strategyId_userId_fkey" FOREIGN KEY ("strategyId", "userId") REFERENCES "Strategy"("id", "userId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "StrategyDeployment" ADD CONSTRAINT "StrategyDeployment_brokerAccountId_userId_fkey" FOREIGN KEY ("brokerAccountId", "userId") REFERENCES "BrokerAccount"("id", "userId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Backtest" ADD CONSTRAINT "Backtest_strategyId_userId_fkey" FOREIGN KEY ("strategyId", "userId") REFERENCES "Strategy"("id", "userId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AgentSignal" ADD CONSTRAINT "AgentSignal_runId_userId_fkey" FOREIGN KEY ("runId", "userId") REFERENCES "AgentRun"("id", "userId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AutoTradeConfig" ADD CONSTRAINT "AutoTradeConfig_brokerAccountId_userId_fkey" FOREIGN KEY ("brokerAccountId", "userId") REFERENCES "BrokerAccount"("id", "userId") ON DELETE NO ACTION ON UPDATE CASCADE;
