-- AuditLog.actorId (who acted, beside userId: whose data) with an index for "what did this actor do", and
-- Session.createdAt, from which the api enforces the 30-day absolute session lifetime. Generated by
-- `prisma migrate dev --create-only`; this comment and IF NOT EXISTS were added by hand, so a partially applied run
-- can be re-applied (Prisma >= 7.4 runs migration.sql statement by statement, not atomically).
--
-- - AuditLog: a nullable column without a default changes only the catalog. No row is rewritten and no row trigger
--   fires; the ENABLE ALWAYS guard triggers keep their mode, because nothing re-creates them. The actor CHECKs come
--   in migrations/<timestamp>_audit_actor_checks.
-- - Session: CURRENT_TIMESTAMP is stable, so PostgreSQL >= 11 adds the column without rewriting the table. Existing
--   rows get the time of this migration.

-- AlterTable
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "actorId" TEXT;

-- AlterTable
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "AuditLog_actorId_createdAt_idx" ON "AuditLog"("actorId", "createdAt" DESC);
