import { describe, expect, it } from "vitest";

import * as shared from "../index";

describe("@finlytics/shared entry point", () => {
  it("exports exactly the documented runtime API", () => {
    expect(Object.keys(shared).sort()).toEqual(
      [
        // types/result
        "err",
        "ok",
        // schemas/enums
        "BROKER_CODES",
        "BrokerCodeSchema",
        "EXCHANGES",
        "ExchangeSchema",
        "OPTION_TYPES",
        "OptionTypeSchema",
        "ORDER_TYPES",
        "OrderTypeSchema",
        "PRISMA_ENUM_MIRRORS",
        "PRODUCT_TYPES",
        "ProductTypeSchema",
        "ROLES",
        "RoleSchema",
        "SEGMENTS",
        "SegmentSchema",
        "VALIDITIES",
        "ValiditySchema",
        // schemas/errors
        "ERROR_CODES",
        "ERROR_HTTP_STATUS",
        "ERROR_TITLES",
        "ErrorCodeSchema",
        "FieldErrorSchema",
        "isKnownErrorCode",
        "isProblemDetails",
        "isRetryableErrorCode",
        "MAX_FIELD_ERRORS",
        "PROBLEM_JSON_MEDIA_TYPE",
        "PROBLEM_LIMITS",
        "ProblemDetailsSchema",
        "problemTypeUrl",
        "REQUEST_ID_PATTERN",
        "RETRYABLE_ERROR_CODES",
        // schemas/http
        "HEADERS",
        "IdempotencyKeySchema",
        "RequestIdSchema",
        // schemas/session
        "hashSessionToken",
        "SESSION_COOKIE_NAME",
        "SESSION_LIMITS",
        "SESSION_TOKEN_PATTERN",
        // email
        "normalizeEmail",
        // schemas/me
        "MeSchema",
        // schemas/health
        "HealthLiveSchema",
        "HealthReadySchema",
        // money
        "DecimalStringSchema",
        "formatInr",
        "formatInrCompact",
        "isOnTick",
        "MoneySchema",
        "PriceSchema",
        "QuantitySchema",
        "roundToTick",
        "toDecimal",
        "toDecimalString",
        // constants/exchanges
        "holidayCalendarFor",
        "SEGMENT_TOKEN_INFO",
        "SEGMENT_TOKENS",
        "segmentTokenFor",
        "SegmentTokenSchema",
        // instrument-key
        "canonicalStrike",
        "dateToExpiry",
        "expiryToDate",
        "formatInstrumentKey",
        "instrumentKeyFromParam",
        "InstrumentKeySchema",
        "instrumentKeyToParam",
        "isInstrumentKey",
        "MAX_INSTRUMENT_KEY_LENGTH",
        "normalizeInstrumentKey",
        "parseInstrumentKey",
        // schemas/user-settings
        "DEFAULT_USER_SETTINGS",
        "mergeUserSettings",
        "NOTIFICATION_CATEGORIES",
        "NotificationCategorySchema",
        "parseUserSettings",
        "parseUserSettingsWithIssues",
        "UserSettingsPatchSchema",
        "UserSettingsSchema",
        // schemas/realtime
        "RT_COALESCE_MS",
        "RT_CONNECT_ERRORS",
        "RT_EVENTS",
        "RT_FEED_STATES",
        "RT_MAX_DEPTH_KEYS",
        "RT_MAX_KEYS_PER_MESSAGE",
        "RT_NAMESPACE",
        "RT_PATH",
        "RT_REJECT_REASONS",
        "RtDepthAckSchema",
        "RtDepthLevelSchema",
        "RtDepthSchema",
        "RtDepthSubscribeSchema",
        "RtFeedStateSchema",
        "RtQuoteBatchSchema",
        "RtQuoteRowSchema",
        "RtRejectReasonSchema",
        "RtStatusSchema",
        "RtSubscribeAckSchema",
        "RtSubscribeSchema",
        "RtUnsubscribeAckSchema",
        "RtUnsubscribeSchema",
        // schemas/candles
        "CANDLE_TIMEFRAME_MS",
        "CANDLE_TIMEFRAMES",
        "CandleBarSchema",
        "CandleListSchema",
        "CandlesQuerySchema",
        "CandleTimeframeSchema",
        "CandleTimeSchema",
        "MAX_CANDLES_PER_REQUEST",
        "UDF_RESOLUTIONS",
        "UDF_SUPPORTED_RESOLUTIONS",
        "UdfConfigSchema",
        "UdfHistoryQuerySchema",
        "UdfHistorySchema",
        "UdfSearchQuerySchema",
        "UdfSearchResultSchema",
        "UdfSymbolInfoSchema",
        "UdfSymbolQuerySchema",
        // schemas/brokers
        "BROKER_ACCOUNT_STATUSES",
        "BROKER_CALLBACK_ERRORS",
        "BrokerAccountIdSchema",
        "BrokerAccountLabelSchema",
        "BrokerAccountListSchema",
        "BrokerAccountStatusSchema",
        "BrokerAccountViewSchema",
        "BrokerAuthRedirectSchema",
        "BrokerCallbackErrorSchema",
        "BrokerLimitsSchema",
        "ConnectDhanSchema",
        "ConnectPaperSchema",
        "ConnectUpstoxSchema",
        "UpdateBrokerAccountSchema",
        "UpstoxCallbackQuerySchema",
        // schemas/instruments
        "INSTRUMENT_SEARCH_MAX_LIMIT",
        "InstrumentListSchema",
        "InstrumentSchema",
        "InstrumentSearchQuerySchema",
        "InstrumentSyncRequestSchema",
        "InstrumentSyncResultSchema",
        // schemas/watchlists
        "AddWatchlistItemSchema",
        "CreateWatchlistSchema",
        "MAX_WATCHLIST_REORDER_ITEMS",
        "ReorderWatchlistItemsSchema",
        "UpdateWatchlistSchema",
        "WatchlistIdSchema",
        "WatchlistItemSchema",
        "WatchlistListSchema",
        "WatchlistNameSchema",
        "WatchlistSchema",
        // schemas/quotes
        "MAX_QUOTE_KEYS",
        "QuoteDepthQuerySchema",
        "QuoteSchema",
        "quoteFromHash",
        "QuotesQuerySchema",
        "QuotesResultSchema",
        // schemas/market
        "ExchangeStatusSchema",
        "FeedInfoSchema",
        "MARKET_EXCHANGES",
        "MARKET_INDEX_KEYS",
        "MARKET_PHASES",
        "MarketBreadthSchema",
        "MarketExchangeSchema",
        "MarketOverviewSchema",
        "MarketPhaseSchema",
        "MarketQuoteSchema",
        "NIFTY_50_KEYS",
        "TICKER_INDEX_IDS",
        // schemas/portfolio
        "FundsViewSchema",
        "HoldingsViewSchema",
        "HoldingViewSchema",
        "PortfolioQuerySchema",
        "PositionsViewSchema",
        "PositionViewSchema",
      ].sort(),
    );
  });
});
