-- Phase 1 (brokers & market data, plan P3 and P6). Generated by `prisma migrate dev --create-only`, then rewritten by
-- hand so that every statement is idempotent: Prisma >= 7.4 runs migration.sql statement by statement, not
-- atomically, so a partially applied run must be re-applicable as is.
--
-- - BrokerAccount vault (P3): the shared "encIv" is replaced by one 96-bit IV per ciphertext (data key, credentials,
--   client id, app credentials), each ciphertext stored with its GCM tag. "brokerClientIdEnc" becomes BYTEA (it was
--   TEXT). No code wrote BrokerAccount before this migration (there was no vault), so the table is empty everywhere;
--   on a table with rows, adding "encKeyIv" NOT NULL fails loudly instead of keeping undecryptable rows.
-- - "expiryNotifiedAt": the broker-token-expiry job writes each reminder once per token (P7).
-- - Instrument."tradingSymbol" with a trigram index, for instrument search.
-- - InstrumentBrokerToken (P6, carry-forward 6): (broker, token) → canonical instrument key, for the market feed.
-- - CHECKs (hand-written; Prisma never generates or diffs them): each ciphertext has its IV, every IV is 12 bytes, the
--   wrapped data key is 48 bytes (32 + tag) and an ACTIVE account has credentials.

-- AlterTable
ALTER TABLE "BrokerAccount" DROP COLUMN IF EXISTS "encIv";
ALTER TABLE "BrokerAccount" ADD COLUMN IF NOT EXISTS "appCredentialsEnc" BYTEA;
ALTER TABLE "BrokerAccount" ADD COLUMN IF NOT EXISTS "appCredentialsIv" BYTEA;
ALTER TABLE "BrokerAccount" ADD COLUMN IF NOT EXISTS "brokerClientIdIv" BYTEA;
ALTER TABLE "BrokerAccount" ADD COLUMN IF NOT EXISTS "credentialsIv" BYTEA;
ALTER TABLE "BrokerAccount" ADD COLUMN IF NOT EXISTS "encKeyIv" BYTEA NOT NULL;
ALTER TABLE "BrokerAccount" ADD COLUMN IF NOT EXISTS "expiryNotifiedAt" TIMESTAMP(3);
ALTER TABLE "BrokerAccount" ALTER COLUMN "encryptedCredentials" DROP NOT NULL;

-- Retype "brokerClientIdEnc" TEXT → BYTEA, only while it is still TEXT (a re-run leaves the BYTEA column alone).
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'BrokerAccount' AND column_name = 'brokerClientIdEnc'
      AND data_type = 'text'
  ) THEN
    ALTER TABLE "BrokerAccount" DROP COLUMN "brokerClientIdEnc";
  END IF;
END
$$;
ALTER TABLE "BrokerAccount" ADD COLUMN IF NOT EXISTS "brokerClientIdEnc" BYTEA;

-- AlterTable
ALTER TABLE "Instrument" ADD COLUMN IF NOT EXISTS "tradingSymbol" TEXT;

-- CreateTable
CREATE TABLE IF NOT EXISTS "InstrumentBrokerToken" (
    "broker" "BrokerCode" NOT NULL,
    "token" TEXT NOT NULL,
    "instrumentKey" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "seenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "InstrumentBrokerToken_pkey" PRIMARY KEY ("broker","token")
);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "InstrumentBrokerToken_instrumentKey_broker_idx" ON "InstrumentBrokerToken"("instrumentKey", "broker");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "InstrumentBrokerToken_broker_isActive_seenAt_idx" ON "InstrumentBrokerToken"("broker", "isActive", "seenAt");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "BrokerAccount_userId_createdAt_idx" ON "BrokerAccount"("userId", "createdAt");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "instrument_trading_symbol_trgm" ON "Instrument" USING GIN ("tradingSymbol" gin_trgm_ops);

-- AddForeignKey
ALTER TABLE "InstrumentBrokerToken" DROP CONSTRAINT IF EXISTS "InstrumentBrokerToken_instrumentKey_fkey";
ALTER TABLE "InstrumentBrokerToken" ADD CONSTRAINT "InstrumentBrokerToken_instrumentKey_fkey" FOREIGN KEY ("instrumentKey") REFERENCES "Instrument"("key") ON DELETE CASCADE ON UPDATE CASCADE;

-- Vault CHECKs (hand-written).
ALTER TABLE "BrokerAccount" DROP CONSTRAINT IF EXISTS "BrokerAccount_vault_check";
ALTER TABLE "BrokerAccount" ADD CONSTRAINT "BrokerAccount_vault_check" CHECK (
  octet_length("encKeyWrapped") = 48
  AND octet_length("encKeyIv") = 12
  AND ("brokerClientIdEnc" IS NULL) = ("brokerClientIdIv" IS NULL)
  AND ("encryptedCredentials" IS NULL) = ("credentialsIv" IS NULL)
  AND ("appCredentialsEnc" IS NULL) = ("appCredentialsIv" IS NULL)
  AND ("brokerClientIdIv" IS NULL OR octet_length("brokerClientIdIv") = 12)
  AND ("credentialsIv" IS NULL OR octet_length("credentialsIv") = 12)
  AND ("appCredentialsIv" IS NULL OR octet_length("appCredentialsIv") = 12)
  AND ("status" <> 'ACTIVE' OR "encryptedCredentials" IS NOT NULL)
);
